
    version: '3'
    services:
      postgres:
        image: 'postgres:11'
        container_name: 'jakson-postgres-test'
        command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
        ports:
          - '5432:5432'
    
  